routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout','Controller@logout') -> name('logout');

Route::group(['middleware' => 'CheckLogin'],function()
{
    Route::group(['middleware' => 'CheckGiaoVu'],function()
    {

        Route::group(['frefix' => 'GiaoVien','as' =>'GiaoVien.'],function(){
            Route::get('giao_vien','GiaoVienController@view_all') -> name('view_all');
            Route::get('giao_vien/view_insert','GiaoVienController@view_insert') -> name('view_insert');
            Route::post('giao_vien/process_insert','GiaoVienController@process_insert') -> name('process_insert');
            Route::get('giao_vien/view_update/{ma}','GiaoVienController@view_update') -> name('view_update');
            Route::post('giao_vien/update/{ma}','GiaoVienController@update') -> name('update');
            Route::get('giao_vien/delete/{ma}','GiaoVienController@delete') -> name('delete');
            Route::post('giao_vien/search','GiaoVienController@search') -> name('search');

        });

        Route::group(['frefix' => 'nganh_hoc','as' =>'nganh_hoc.'],function(){
            Route::get('nganh_hoc','NganhHocController@view_all') -> name('view_all');
            Route::get('nganh_hoc/view_insert','NganhHocController@view_insert') -> name('view_insert');
            Route::post('nganh_hoc/process_insert','NganhHocController@process_insert') -> name('process_insert');
            Route::get('nganh_hoc/view_update/{ma}','NganhHocController@view_update') -> name('view_update');
            Route::post('nganh_hoc/update/{ma}','NganhHocController@update') -> name('update');
            Route::get('nganh_hoc/delete/{ma}','NganhHocController@delete') -> name('delete');
            Route::post('nganh_hoc/search','NganhHocController@search') -> name('search');
        });

        Route::group(['frefix' => 'khoa','as' =>'khoa.'],function(){
            Route::get('khoa','KhoaController@view_all') -> name('view_all');
            Route::get('khoa/view_insert','KhoaController@view_insert') -> name('view_insert');
            Route::post('khoa/process_insert','KhoaController@process_insert') -> name('process_insert');
            Route::get('khoa/view_update/{ma}','KhoaController@view_update') -> name('view_update');
            Route::post('khoa/update/{ma}','KhoaController@update') -> name('update');
            Route::get('khoa/delete/{ma}','KhoaController@delete') -> name('delete');
            Route::post('khoa/search','KhoaController@search') -> name('search');
        });

        Route::group(['frefix' => 'mon_hoc','as' =>'mon_hoc.'],function(){
            Route::get('mon_hoc','MonHocController@view_all') -> name('view_all');
            Route::get('mon_hoc/view_insert','MonHocController@view_insert') -> name('view_insert');
            Route::post('mon_hoc/process_insert','MonHocController@process_insert') -> name('process_insert');
            Route::get('mon_hoc/view_update/{ma}','MonHocController@view_update') -> name('view_update');
            Route::post('mon_hoc/update/{ma}','MonHocController@update') -> name('update');
            Route::get('mon_hoc/delete/{ma}','MonHocController@delete') -> name('delete');
            Route::post('mon_hoc/search','MonHocController@search') -> name('search');
        });

        Route::group(['frefix' => 'lop','as' =>'lop.'],function(){
            Route::get('lop','LopController@view_all') -> name('view_all');
            Route::get('lop/view_insert','LopController@view_insert') -> name('view_insert');
            Route::post('lop/process_insert','LopController@process_insert') -> name('process_insert');
            Route::get('lop/view_update/{ma}','LopController@view_update') -> name('view_update');
            Route::post('lop/update/{ma}','LopController@update') -> name('update');
            Route::get('lop/delete/{ma}','LopController@delete') -> name('delete');
            Route::post('lop/search','LopController@search') -> name('search');
        });

        Route::group(['frefix' => 'sinh_vien','as' =>'sinh_vien.'],function(){
            Route::get('sinh_vien','SinhVienController@view_all') -> name('view_all');
            Route::get('ajax','SinhVienController@ajax') -> name('ajax');
            Route::get('ajax_lop','SinhVienController@ajax_lop') -> name('ajax_lop');
            Route::get('sinh_vien/view_insert_all','SinhVienController@view_insert_all') -> name('view_insert_all');
            Route::get('excel','SinhVienController@insert_excel') -> name('insert_excel');
            Route::get('sinh_vien/view_insert','SinhVienController@view_insert') -> name('view_insert');
            Route::post('sinh_vien/process_insert','SinhVienController@process_insert') -> name('process_insert');
            Route::post('sinh_vien/excel','SinhVienController@process_excel') -> name('process_excel');
            Route::get('sinh_vien/view_update/{ma}','SinhVienController@view_update') -> name('view_update');
            Route::post('sinh_vien/update/{ma}','SinhVienController@update') -> name('update');
            Route::post('sinh_vien/delete','SinhVienController@delete') -> name('delete');
            Route::post('search','SinhVienController@search') -> name('search');
        });
        Route::group(['frefix' => 'tai_khoan','as' =>'tai_khoan.'],function(){
            Route::get('tai_khoan','TaiKhoanController@thong_tin') -> name('thong_tin');
        });
    });

    Route::group(['frefix' => 'phan_cong','as' =>'phan_cong.'],function(){
        Route::get('phan_cong','PhanCongController@view_all') -> name('view_all') ->middleware('CheckGiaoVu');
        Route::get('ajax_nganh','PhanCongController@ajax_nganh') -> name('ajax_nganh') ->middleware('CheckGiaoVu');
        Route::get('phan_cong_gv','PhanCongController@gv_phan_cong') -> name('gv_phan_cong') ->middleware('CheckGiaoVien');
        Route::get('phan_cong/view_insert','PhanCongController@view_insert') -> name('view_insert') -> middleware('CheckGiaoVu');
        Route::post('phan_cong/process_insert','PhanCongController@process_insert') -> name('process_insert') ->middleware('CheckGiaoVu');
        Route::get('phan_cong/view_update/{ma_lop},{ma_mon}','PhanCongController@view_update') -> name('view_update') -> middleware('CheckGiaoVu');
        Route::post('phan_cong/update/{ma}','PhanCongController@update') -> name('update') -> middleware('CheckGiaoVu');

        Route::get('phan_cong/delete/{ma_lop},{ma_mon}','PhanCongController@delete') -> name('delete') -> middleware('CheckGiaoVu');

    });

    Route::group(['frefix' => 'diem_danh','as' =>'diem_danh.'],function(){
        Route::get('diem_danh','DiemDanhController@view_all') -> name('view_all') ->middleware('CheckGiaoVien');
        Route::post('diem_danh','DiemDanhController@view_diem_danh') -> name('view_diem_danh') ->middleware('CheckGiaoVien');
        Route::post('process_diem_danh','DiemDanhController@process_diem_danh') -> name('process_diem_danh') ->middleware('CheckGiaoVien');
        Route::get('view_update/{ma}','DiemDanhController@view_update') -> name('view_update');
        Route::get('diem_danh/lich_su','DiemDanhController@lich_su') -> name('lich_su')
            ->middleware('CheckGiaoVien');
        Route::get('diem_danh/lich_su_all','DiemDanhController@lich_su_all') -> name('lich_su_all') ->middleware('CheckGiaoVu');
    });


    Route::get('giao_vu','Controller@giao_vu') -> name('giao_vu') -> middleware('CheckGiaoVu');
    Route::get('trang_giao_vien','Controller@giao_vien') -> name('giao_vien')-> middleware('CheckGiaoVien');

});
Route::get('forgot_password','Controller@forgot_password')->name('forgot_password');
Route::get('','Controller@view_login')->name('view_login');
Route::post('sendemail','Controller@sendemail')->name('sendemail');
Route::post('process_login','Controller@process_login') -> name('process_login');

app/Models/NganhHoc.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class NganhHoc extends Model
{
    protected $table = 'nganh_hoc';
    protected $fillable = [
        'ten_nganh'
    ];
    public $timestamps = false;
    protected $primaryKey = 'ma';
}

app/Http/Controllers/NganhHocController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\NganhHoc;

class NganhHocController extends Controller
{
    public function view_all()
    {
        $array_nganh = NganhHoc::paginate(10);
        return view('nganh_hoc.view_all',compact('array_nganh'));
    }
    public function view_insert()
    {
        return view('nganh_hoc.view_insert');
    }
    public function process_insert(Request $rq)
    {
        $nganh = $rq -> ten_nganh;
        if(NganhHoc::where('ten_nganh','=',$nganh) -> first()){
            return redirect() -> route('nganh_hoc.view_insert') -> with('error','/');
        }
        NganhHoc::create($rq -> all());
        return redirect('nganh_hoc') -> with('success','/');
    }
    public function view_update($ma,Request $rq)
    {
        $nganh_hoc = NganhHoc::find($ma);
        return view('nganh_hoc.view_update',compact('nganh_hoc'));
    }
    public function update($ma,Request $rq)
    {
        $nganh = $rq -> ten_nganh;
        if(NganhHoc::where('ma','=',$ma) -> where('ten_nganh','=',$nganh) ->first()){
            NganhHoc::find($ma) -> update($rq -> all());
        }
        else if(NganhHoc::where('ten_nganh','=',$nganh) -> first()){
            return redirect() -> route('nganh_hoc.view_update',['ma' => $ma]) -> with('error','/');
        }
        NganhHoc::find($ma) -> update($rq -> all());
        return redirect('nganh_hoc') -> with('success_update','/');
    }
    public function delete($ma)
    {
        NganhHoc::destroy($ma);
        return redirect('nganh_hoc');
    }
    public function search(Request $rq){
        $data = $rq -> search;
        $array_nganh = NganhHoc::where('ten_nganh','LIKE', '%'.$data.'%') -> paginate(10);

        return view('nganh_hoc.search',compact('array_nganh'));
    }
}

resources/views/nganh_hoc/search.blade.php
@extends('layout.master.master')
@section('search')
    <div class="search-bar">
        <form action="{{ route('nganh_hoc.search') }}" method="POST" class="search-bar ">
            @csrf
            <input class="search-input form-control" type="search" name="search" placeholder="Tìm kiếm ngành học" />
            <a href="#" class="close-search toggle-search" data-target="#search-wrap">
                <i class="mdi mdi-close-circle"></i>
            </a>
        </form>
    </div>
@endsection
@section('content')

    <!DOCTYPE html>
    <html>
    <head>
        <title></title>
        <script>
            function allow(){
                var check = confirm("Bạn muốn xóa không");
                if (check == true){
                    return true;
                }else {
                    return false;
                }
            }
        </script>
    </head>
    <body>
    <div>
        @if (Session::has('success'))
            <script>
                alert("Thêm thành công.");
            </script>
        @elseif(Session::has('success_update'))
            <script>
                alert("sửa thành công.");
            </script>
        @endif
    </div>
    <h1>Danh Sách Ngành Học</h1>
    <br>
    <br>
    <table class="table table-bordered mb-0" style="text-align: center; width: 70%">
        <tr>
            <th>Mã ngành</th>
            <th>Tên ngành</th>
            <th>Tác vụ</th>
        </tr>
        @foreach ($array_nganh as $nganh)
            <tr>
                <td>
                    {{ $nganh -> ma }}
                </td>
                <td>
                    {{ $nganh -> ten_nganh }}
                </td>
                <td>
                    <table style="width: 100%">
                        <td>
                            <a href="{{ route('nganh_hoc.view_update',['ma' => $nganh->ma]) }}">
                                <i class="mdi mdi-pencil-outline"></i>
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('nganh_hoc.delete',['ma' => $nganh->ma]) }}" onclick="return allow()">
                                <i class="dripicons-trash"></i>
                            </a>
                        </td>
                    </table>
                </td>
            </tr>
        @endforeach
    </table>
    <span style="text-align: center">{{ $array_nganh -> render() }}</span>
    </body>
    </html>
@endsection

resources/views/nganh_hoc/view_all.blade.php
@extends('layout.master.master')
@section('search')
	<div class="search-bar">
		<form action="{{ route('nganh_hoc.search') }}" method="POST" class="search-bar ">
			@csrf
			<input class="search-input form-control" type="search" name="search" placeholder="Tìm kiếm ngành học" />
			<a href="#" class="close-search toggle-search" data-target="#search-wrap">
				<i class="mdi mdi-close-circle"></i>
			</a>
		</form>
	</div>
@endsection
@section('content')

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script>
		function allow(){
			var check = confirm("Bạn muốn xóa không");
			if (check == true){
				return true;
			}else {
				return false;
			}
		}
	</script>
</head>
<body>
<div>
	@if (Session::has('success'))
		<script>
			alert("Thêm thành công.");
		</script>
	@elseif(Session::has('success_update'))
		<script>
			alert("sửa thành công.");
		</script>
	@endif
</div>
	<h1>Danh Sách Ngành Học</h1>
	<br>
	<br>
	<table class="table table-bordered mb-0" style="text-align: center; width: 70%">
		<tr>
			<th>Mã ngành</th>
			<th>Tên ngành</th>
			<th>Tác vụ</th>
		</tr>
		@foreach ($array_nganh as $nganh)
			<tr>
				<td>
					{{ $nganh -> ma }}
				</td>
				<td>
					{{ $nganh -> ten_nganh }}
				</td>
				<td>
					<table style="width: 100%">
						<td>
							<a href="{{ route('nganh_hoc.view_update',['ma' => $nganh->ma]) }}">
								<i class="mdi mdi-pencil-outline"></i>
							</a>
						</td>
						<td>
							<a href="{{ route('nganh_hoc.delete',['ma' => $nganh->ma]) }}" onclick="return allow()">
								<i class="dripicons-trash"></i>
							</a>
						</td>
					</table>
				</td>
			</tr>
		@endforeach
	</table>
<span style="text-align: center">{{ $array_nganh -> render() }}</span>
</body>
</html>
@endsection

resources/views/nganh_hoc/view_insert.blade.php
@extends('layout.master.master')

@section('content')

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript">
		function validateForm() {
			var name = document.getElementById('nganh').value;
			if (name == "") {
				alert("Tên không được để trống:");
				return false;
			}
			return true;
		}
	</script>
</head>
<body>
@if (Session::has('error'))
	<script>
		alert("Tên lày đã tồn tại");
	</script>
@endif
	<h3>Thêm Ngành Học</h3>
	<br>
	<br>
	<form method="POST" action="{{ route('nganh_hoc.process_insert') }}" onsubmit="return validateForm()">
		@csrf
		<div class="form-group">
			<label>Nhập tên ngành</label>
			<input type="text" name="ten_nganh" id="nganh" class="form-control" style="width: 30%;">
		</div>
		<button class="btn btn-primary waves-effect waves-light mr-1">Thêm</button>
		<button type="reset" class="btn btn-secondary waves-effect">Xóa</button>
	</form>
</body>
</html>
@endsection

resources/views/nganh_hoc/view_update.blade.php
@extends('layout.master.master')

@section('content')

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript">
		function validateForm() {
			var name = document.getElementById('nganh').value;
			if (name == "") {
				alert("Tên không được để trống:");
				return false;
			}else{
				var result = confirm("Bạn có muốn chỉnh sửa không ?");
				if(result == true){
					return true;
				}else {
					return false;
				}
			}
			return true;
		}
	</script>
</head>
<body>
<div>
	@if (Session::has('erro'))
		<script>
			alert("Tên lày đã tồn tại.");
		</script>
	@endif
</div>
	<h3>sửa thông tin</h3>
	<br>
	<br>
	<form method="POST" action="{{ route('nganh_hoc.update',['ma' => $nganh_hoc -> ma]) }}" onsubmit="return validateForm()">
		{{ csrf_field() }}
		<div class="form-group">
			<label>Nhập tên ngành</label>
			<input type="text" name="ten_nganh" id="nganh" value="{{ $nganh_hoc -> ten_nganh }}"class="form-control" style="width: 30%">
		</div>
		<button class="btn btn-primary waves-effect waves-light mr-1">Sửa</button>
		<button type="reset" class="btn btn-secondary waves-effect">Khôi phục</button>
	</form>
</body>
</html>
@endsection