routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout','Controller@logout') -> name('logout');

Route::group(['middleware' => 'CheckLogin'],function()
{
    Route::group(['middleware' => 'CheckGiaoVu'],function()
    {

        Route::group(['frefix' => 'GiaoVien','as' =>'GiaoVien.'],function(){
            Route::get('giao_vien','GiaoVienController@view_all') -> name('view_all');
            Route::get('giao_vien/view_insert','GiaoVienController@view_insert') -> name('view_insert');
            Route::post('giao_vien/process_insert','GiaoVienController@process_insert') -> name('process_insert');
            Route::get('giao_vien/view_update/{ma}','GiaoVienController@view_update') -> name('view_update');
            Route::post('giao_vien/update/{ma}','GiaoVienController@update') -> name('update');
            Route::get('giao_vien/delete/{ma}','GiaoVienController@delete') -> name('delete');
            Route::post('giao_vien/search','GiaoVienController@search') -> name('search');

        });

        Route::group(['frefix' => 'nganh_hoc','as' =>'nganh_hoc.'],function(){
            Route::get('nganh_hoc','NganhHocController@view_all') -> name('view_all');
            Route::get('nganh_hoc/view_insert','NganhHocController@view_insert') -> name('view_insert');
            Route::post('nganh_hoc/process_insert','NganhHocController@process_insert') -> name('process_insert');
            Route::get('nganh_hoc/view_update/{ma}','NganhHocController@view_update') -> name('view_update');
            Route::post('nganh_hoc/update/{ma}','NganhHocController@update') -> name('update');
            Route::get('nganh_hoc/delete/{ma}','NganhHocController@delete') -> name('delete');
            Route::post('nganh_hoc/search','NganhHocController@search') -> name('search');
        });

        Route::group(['frefix' => 'khoa','as' =>'khoa.'],function(){
            Route::get('khoa','KhoaController@view_all') -> name('view_all');
            Route::get('khoa/view_insert','KhoaController@view_insert') -> name('view_insert');
            Route::post('khoa/process_insert','KhoaController@process_insert') -> name('process_insert');
            Route::get('khoa/view_update/{ma}','KhoaController@view_update') -> name('view_update');
            Route::post('khoa/update/{ma}','KhoaController@update') -> name('update');
            Route::get('khoa/delete/{ma}','KhoaController@delete') -> name('delete');
            Route::post('khoa/search','KhoaController@search') -> name('search');
        });

        Route::group(['frefix' => 'mon_hoc','as' =>'mon_hoc.'],function(){
            Route::get('mon_hoc','MonHocController@view_all') -> name('view_all');
            Route::get('mon_hoc/view_insert','MonHocController@view_insert') -> name('view_insert');
            Route::post('mon_hoc/process_insert','MonHocController@process_insert') -> name('process_insert');
            Route::get('mon_hoc/view_update/{ma}','MonHocController@view_update') -> name('view_update');
            Route::post('mon_hoc/update/{ma}','MonHocController@update') -> name('update');
            Route::get('mon_hoc/delete/{ma}','MonHocController@delete') -> name('delete');
            Route::post('mon_hoc/search','MonHocController@search') -> name('search');
        });

        Route::group(['frefix' => 'lop','as' =>'lop.'],function(){
            Route::get('lop','LopController@view_all') -> name('view_all');
            Route::get('lop/view_insert','LopController@view_insert') -> name('view_insert');
            Route::post('lop/process_insert','LopController@process_insert') -> name('process_insert');
            Route::get('lop/view_update/{ma}','LopController@view_update') -> name('view_update');
            Route::post('lop/update/{ma}','LopController@update') -> name('update');
            Route::get('lop/delete/{ma}','LopController@delete') -> name('delete');
            Route::post('lop/search','LopController@search') -> name('search');
        });

        Route::group(['frefix' => 'sinh_vien','as' =>'sinh_vien.'],function(){
            Route::get('sinh_vien','SinhVienController@view_all') -> name('view_all');
            Route::get('ajax','SinhVienController@ajax') -> name('ajax');
            Route::get('ajax_lop','SinhVienController@ajax_lop') -> name('ajax_lop');
            Route::get('sinh_vien/view_insert_all','SinhVienController@view_insert_all') -> name('view_insert_all');
            Route::get('excel','SinhVienController@insert_excel') -> name('insert_excel');
            Route::get('sinh_vien/view_insert','SinhVienController@view_insert') -> name('view_insert');
            Route::post('sinh_vien/process_insert','SinhVienController@process_insert') -> name('process_insert');
            Route::post('sinh_vien/excel','SinhVienController@process_excel') -> name('process_excel');
            Route::get('sinh_vien/view_update/{ma}','SinhVienController@view_update') -> name('view_update');
            Route::post('sinh_vien/update/{ma}','SinhVienController@update') -> name('update');
            Route::post('sinh_vien/delete','SinhVienController@delete') -> name('delete');
            Route::post('search','SinhVienController@search') -> name('search');
        });
        Route::group(['frefix' => 'tai_khoan','as' =>'tai_khoan.'],function(){
            Route::get('tai_khoan','TaiKhoanController@thong_tin') -> name('thong_tin');
        });
    });

    Route::group(['frefix' => 'phan_cong','as' =>'phan_cong.'],function(){
        Route::get('phan_cong','PhanCongController@view_all') -> name('view_all') ->middleware('CheckGiaoVu');
        Route::get('ajax_nganh','PhanCongController@ajax_nganh') -> name('ajax_nganh') ->middleware('CheckGiaoVu');
        Route::get('phan_cong_gv','PhanCongController@gv_phan_cong') -> name('gv_phan_cong') ->middleware('CheckGiaoVien');
        Route::get('phan_cong/view_insert','PhanCongController@view_insert') -> name('view_insert') -> middleware('CheckGiaoVu');
        Route::post('phan_cong/process_insert','PhanCongController@process_insert') -> name('process_insert') ->middleware('CheckGiaoVu');
        Route::get('phan_cong/view_update/{ma_lop},{ma_mon}','PhanCongController@view_update') -> name('view_update') -> middleware('CheckGiaoVu');
        Route::post('phan_cong/update/{ma}','PhanCongController@update') -> name('update') -> middleware('CheckGiaoVu');

        Route::get('phan_cong/delete/{ma_lop},{ma_mon}','PhanCongController@delete') -> name('delete') -> middleware('CheckGiaoVu');

    });

    Route::group(['frefix' => 'diem_danh','as' =>'diem_danh.'],function(){
        Route::get('diem_danh','DiemDanhController@view_all') -> name('view_all') ->middleware('CheckGiaoVien');
        Route::post('diem_danh','DiemDanhController@view_diem_danh') -> name('view_diem_danh') ->middleware('CheckGiaoVien');
        Route::post('process_diem_danh','DiemDanhController@process_diem_danh') -> name('process_diem_danh') ->middleware('CheckGiaoVien');
        Route::get('view_update/{ma}','DiemDanhController@view_update') -> name('view_update');
        Route::get('diem_danh/lich_su','DiemDanhController@lich_su') -> name('lich_su')
            ->middleware('CheckGiaoVien');
        Route::get('diem_danh/lich_su_all','DiemDanhController@lich_su_all') -> name('lich_su_all') ->middleware('CheckGiaoVu');
    });


    Route::get('giao_vu','Controller@giao_vu') -> name('giao_vu') -> middleware('CheckGiaoVu');
    Route::get('trang_giao_vien','Controller@giao_vien') -> name('giao_vien')-> middleware('CheckGiaoVien');

});
Route::get('forgot_password','Controller@forgot_password')->name('forgot_password');
Route::get('','Controller@view_login')->name('view_login');
Route::post('sendemail','Controller@sendemail')->name('sendemail');
Route::post('process_login','Controller@process_login') -> name('process_login');

app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SinhVien extends Model
{
    protected $table = 'sinh_vien';
    protected $fillable = [
        'ho_ten',
        'gioi_tinh',
        'ngay_sinh',
        'dia_chi',
        'so_dien_thoai',
        'email',
        'ma_lop'
    ];
    public $timestamps = false;
    protected $primaryKey = 'ma';

    public function lop()
    {
        return $this -> belongsTo('App\Models\Lop','ma_lop');
    }

    public function getTenGioiTinhAttribute($gioi_tinh)
    {
        if ($this -> gioi_tinh == 0){
            return "Nam";
        }
        else{
            return "Nữ";
        }
    }
}

app/Http/Controllers/SinhVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SinhVien;
use App\Models\Lop;
use App\Models\NganhHoc;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\SinhVienImport;

class SinhVienController extends Controller
{
    public function view_all()
    {
        $array_sinh_vien = SinhVien::join('lop','sinh_vien.ma_lop','=','lop.ma')
            -> select('sinh_vien.*','lop.ten_lop') -> paginate(10);
        return view('sinh_vien.view_all',compact('array_sinh_vien'));
    }

    public function view_insert_all()
    {
        return view('sinh_vien.view_insert_all');
    }
    public function view_insert()
    {
        $lop = Lop::get();
        return view('sinh_vien.view_insert',compact('lop'));
    }

    public function insert_excel()
    {
        return view('sinh_vien.insert_excel');
    }
    public function process_excel(Request $rq)
    {
        Excel::import(new SinhVienImport, $rq -> file_excel);
        return redirect('sinh_vien');
    }
    public function process_insert(Request $rq)
    {
        SinhVien::create($rq -> all());
        return redirect('sinh_vien') -> with('success','/');
    }
    public function view_update($ma)
    {
        $lop = Lop::get();
        $sinh_vien = SinhVien::where('ma', $ma) -> first();
        return view('sinh_vien.view_update',compact('sinh_vien','lop'));
    }
    public function update($ma,Request $rq)
    {
        SinhVien::find($ma)-> update($rq -> all());
        return redirect() -> route('sinh_vien.view_all');
    }
    public function search(Request $rq){
        $data = $rq -> search;
        $array_sinh_vien = SinhVien::where('ho_ten','LIKE', '%'.$data.'%')
                            -> orWhere('dia_chi','LIKE', '%'.$data.'%')
                            -> orWhere('so_dien_thoai','LIKE', '%'.$data.'%')
                            -> orWhere('ngay_sinh','LIKE', '%'.$data.'%')
                            -> orWhere('email','LIKE', '%'.$data.'%')
                            -> join('lop','sinh_vien.ma_lop','=','lop.ma')
                            -> orWhere('lop.ten_lop','LIKE', '%'.$data.'%')
                            -> paginate(10);
        return view('sinh_vien.search',compact('array_sinh_vien'));
    }
    public function delete(Request $rq)
    {
        $ma = $rq -> delete;
        foreach ($ma as $ma){
            SinhVien::where('ma',$ma) -> delete();
        }
        return redirect('sinh_vien');

    }
}

resources/views/sinh_vien/insert_excel.blade.php
@extends('layout.master.master')

@section('content')
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div ng-app="app">
		<div ng-controller="UploadController as vm">
			<div class="container">
				<div class="page-header">
					<h1>Thêm sinh viên </h1>
				</div>
				<br>
				<div class="alert alert-info">
					<p>Tải file mẫu tại đây: </p>
					<a href="{{asset('file/file_mau.xlsx')}}" download="mau.xlsx">Dowload</a>
				</div>
				<form method="POST" enctype="multipart/form-data" action="{{ route('sinh_vien.process_excel') }}" onsubmit="return validateForm()">
					{{ csrf_field() }}
					<label>Chọn file excel:</label>
					<input type="file" name="file_excel" class="form-control" id="excel" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
					<br>
					<br>
					<button class="btn btn-primary">Thêm</button>
					<button type="reset" class="btn btn-secondary waves-effect">Xóa</button>
				</form>
			</div>
		</div>
	</div>

</body>
</html>
@endsection

resources/views/sinh_vien/search.blade.php
@extends('layout.master.master')
@section('search')
    <div class="search-bar">
        <form action="{{ route('sinh_vien.search') }}" method="POST" class="search-bar">
            @csrf
            <input class="search-input form-control" type="search" name="search" placeholder="Tìm kiếm sinh viên" />
            <a href="#" class="close-search toggle-search" data-target="#search-wrap">
                <i class="mdi mdi-close-circle"></i>
            </a>
        </form>
    </div>
@endsection

@section('content')

    <!DOCTYPE html>
    <html>
    <head>
        <title></title>
        <script type="text/javascript" src="{{ asset('js/jquery.js') }}"></script>
    </head>
    <body>
    <div>
        @if (Session::has('session'))
            <script>
                alert("Thêm thành công.");
            </script>
        @elseif (Session::has('session_update'))
            <script>
                alert("Sửa thành công.");
            </script>
        @endif
    </div>
    <h3>Danh Sách Sinh Viên</h3>
    <br>
    <br>
    <br>
    <table class="table table-bordered mb-0" id="sinh_vien" style="text-align: center;">
        <tr>
            <th>Họ tên</th>
            <th>Giới tính</th>
            <th>Ngày sinh</th>
            <th>Đỉa chỉ</th>
            <th>Số điện thoại</th>
            <th>Email</th>
            <th>Lớp</th>
            <th>Tác vụ</th>
        </tr>
        @foreach ($array_sinh_vien as $sinh_vien)
            <tr>
                <td>
                    {{ $sinh_vien -> ho_ten }}
                </td>
                <td>
                    @if ($sinh_vien -> gioi_tinh == 0)
                        Nam
                    @else
                        Nữ
                    @endif
                </td>
                <td>
                    {{ $sinh_vien -> ngay_sinh }}
                </td>
                <td>
                    {{ $sinh_vien -> dia_chi }}
                </td>
                <td>
                    {{ $sinh_vien -> so_dien_thoai }}
                </td>
                <td>
                    {{ $sinh_vien -> email }}
                </td>
                <td>
                    {{ $sinh_vien -> ten_lop }}
                </td>
                <td>
                    <table width="100%">
                        <td>
                            <a href="{{ route('sinh_vien.view_update',['ma' => $sinh_vien -> ma]) }}">
                                <i class="mdi mdi-pencil-outline"></i>
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('sinh_vien.delete',['ma' => $sinh_vien -> ma]) }}">
                                <i class="dripicons-trash"></i>
                            </a>
                        </td>
                    </table>
                </td>
            </tr>
        @endforeach
    </table>
    <br>
    <span style="text-align: center">{{ $array_sinh_vien -> render() }}</span>
    </body>
    </html>
@endsection

resources/views/sinh_vien/view_all.blade.php
@extends('layout.master.master')
@section('search')
	<div class="search-bar">
		<form action="{{ route('sinh_vien.search') }}" method="POST" class="search-bar ">
			@csrf
			<input class="search-input form-control" type="search" name="search" placeholder="Tìm kiếm sinh viên" />
			<a href="#" class="close-search toggle-search" data-target="#search-wrap">
				<i class="mdi mdi-close-circle"></i>
			</a>
		</form>
	</div>
@endsection

@section('content')

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript" src="{{ asset('js/jquery.js') }}"></script>
</head>
<body>
<div>
	@if (Session::has('session'))
		<script>
			alert("Thêm thành công.");
		</script>
	@elseif (Session::has('session_update'))
		<script>
			alert("Sửa thành công.");
		</script>
	@elseif (Session::has('search'))
		<script>
			alert("Không tìm thấy dữ liệu.");
		</script>
	@endif

	<form method="post" action="{{ route('sinh_vien.delete') }}">
		@csrf
		<h3>Danh Sách Sinh Viên</h3>
		<br>
		<br>
		<br>
		<table class="table table-bordered mb-0" id="sinh_vien" style="text-align: center;">
			<tr>
				<th>Họ tên</th>
				<th>Giới tính</th>
				<th>Ngày sinh</th>
				<th>Đỉa chỉ</th>
				<th>Số điện thoại</th>
				<th>Email</th>
				<th>Lớp</th>
				<th>Tác vụ</th>
			</tr>
			@foreach ($array_sinh_vien as $sinh_vien)
				<tr>
					<td>
						{{ $sinh_vien -> ho_ten }}
					</td>
					<td>
						@if ($sinh_vien -> gioi_tinh == 0)
							Nam
						@else
							Nữ
						@endif
					</td>
					<td>
						{{ $sinh_vien -> ngay_sinh }}
					</td>
					<td>
						{{ $sinh_vien -> dia_chi }}
					</td>
					<td>
						{{ $sinh_vien -> so_dien_thoai }}
					</td>
					<td>
						{{ $sinh_vien -> email }}
					</td>
					<td>
						{{ $sinh_vien -> ten_lop }}
					</td>
					<td>
						<table width="100%">
							<td>
								<a href="{{ route('sinh_vien.view_update',['ma' => $sinh_vien -> ma]) }}">
									<i class="mdi mdi-pencil-outline"></i>
								</a>
							</td>
							<td>
								<input type="checkbox" name="delete[{{ $sinh_vien -> ma }}]" value="{{ $sinh_vien -> ma }}">
							</td>
						</table>
					</td>
				</tr>
			@endforeach
		</table>
		<div style=" padding-left: 1165px;">
			<button class="btn btn-primary waves-effect waves-light mr-1">Xóa</button>
		</div>
	</form>
</div>
<div id="all"></div>
<br>
<span style="text-align: center">{{ $array_sinh_vien -> render() }}</span>
</body>
</html>
@endsection

resources/views/sinh_vien/view_insert.blade.php
@extends('layout.master.master')
@section('content')
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <script type="text/javascript">
        function validateForm() {
            var name = document.getElementById('name').value;
            var sdt = document.getElementById('sdt').value;
            var email = document.getElementById('email').value;
            var lop = document.getElementById('lop').value;
            if (name == "") {
                alert("Tên không được để trống.");
                return false;
            }
            if (sdt == "") {
                alert("số điện thoại không được để trống.");
                return false;
            }
            if (email == "") {
                alert("email không được để trống.");
                return false;
            }
            if (lop == "0") {
                alert("lớp chưa được chọn.");
                return false;
            }
            return true;
        }
    </script>
</head>
<body>
    <form method="POST" action="{{ route('sinh_vien.process_insert') }}" class="custom-validation" onsubmit="return validateForm()">
        {{ csrf_field() }}
        <h3>Thêm sinh viên</h3>
        <br>
        <br>
        <div class="form-group">
            <label>Họ Tên</label>
            <input class="form-control" type="text" name="ho_ten" id="name" style="width: 40%;">
        </div>

        <div class="form-group">
            <label>Giới Tính</label> &nbsp;&nbsp;&nbsp;
            <input class="" type="radio" name="gioi_tinh" value ="0">&nbsp;Nam&nbsp;&nbsp;
            <input class="" type="radio" name="gioi_tinh" value ="1">&nbsp;Nữ
        </div>

        <div class="form-group">
            <label>Ngày Sinh</label>
            <input class="form-control" type="date" name="ngay_sinh" style="width: 40%;">
        </div>

        <div class="form-group">
            <label>Địa Chỉ</label>
            <input class="form-control" type="text" name="dia_chi" style="width: 40%;">
        </div>

        <div class="form-group">
            <label>Số Điện Thoại</label>
            <input class="form-control" id="sdt" type="text" name="so_dien_thoai" style="width: 40%;">
        </div>

        <div class="form-group">
            <label>Email</label>
            <input class="form-control" type="email" id="email" name="email" style="width: 40%;">
        </div>
        <div class="form-group">
            <label>lớp</label>
            <select name = "ma_lop" class="form-control" id="lop" style="width: 40%; text-align: center;">
                <option selected value="0">--Chọn--</option>
                @foreach ($lop as $lop)
                    <option value="{{ $lop -> ma }}">
                        {{ $lop -> ten_lop }}
                    </option>
                @endforeach
            </select>
        </div>
        <button class="btn btn-primary waves-effect waves-light mr-1">Thêm</button>
        <button type="reset" class="btn btn-secondary waves-effect">Xóa</button>
    </form>
</body>
</html>
@endsection

resources/views/sinh_vien/view_insert_all.blade.php
@extends('layout.master.master')

@section('content')
        <!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<h3>Thêm sinh viên</h3>
<br>
<br>
<br>
<div class="form-group">
    <a href="{{ route('sinh_vien.view_insert') }}" class="btn btn-primary waves-effect waves-light mr-1">Thêm thủ công</a>
    <a href="{{ route('sinh_vien.insert_excel') }}" class="btn btn-primary waves-effect waves-light mr-1">Thêm nhanh</a>
</div>
</body>
</html>
@endsection

resources/views/sinh_vien/view_update.blade.php
@extends('layout.master.master')

@section('content')
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script type="text/javascript">
		function validateForm() {
			var name = document.getElementById('name').value;
			var sdt = document.getElementById('sdt').value;
			var email = document.getElementById('email').value;
			var lop = document.getElementById('lop').value;
			if (name == "") {
				alert("Tên không được để trống.");
				return false;
			}
			if (sdt == "") {
				alert("số điện thoại không được để trống.");
				return false;
			}
			if (email == "") {
				alert("email không được để trống.");
				return false;
			}
			if (lop == "0") {
				alert("lớp chưa được chọn.");
				return false;
			}else{
				var result = confirm("Bạn có muốn chỉnh sửa không ?");
				if(result == true){
					return true;
				}else {
					return false;
				}
			}
		}
	</script>
</head>
<body>
	<h3>sửa thông tin</h3>
	<br>
	<br>
	<form method="POST" action="{{ route('sinh_vien.update',['ma' => $sinh_vien -> ma]) }}" onsubmit="return validateForm()" class="table">
		{{ csrf_field() }}
		<div class="form-group">
			<label>Họ Tên</label>
			<input class="form-control" type="text" name="ho_ten" value="{{ $sinh_vien -> ho_ten }}" id="name" style="width: 40%;">
		</div>

		<div class="form-group">
			<label>Giới Tính</label> &nbsp;&nbsp;&nbsp;
			<input type="radio" name="gioi_tinh" value ="0"
			@if ($sinh_vien -> gioi_tinh == 0)
				checked
			@endif>Nam &ensp;
			<input type="radio" name="gioi_tinh" value ="1"
				   @if ($sinh_vien -> gioi_tinh ==1)
				   checked
					@endif
			>Nữ
		</div>

		<div class="form-group">
			<label>Ngày Sinh</label>
			<input class="form-control" type="date" name="ngay_sinh" value="{{ $sinh_vien -> ngay_sinh }}" style="width: 40%;">
		</div>

		<div class="form-group">
			<label>Địa Chỉ</label>
			<input class="form-control" type="text" name="dia_chi" value="{{ $sinh_vien -> dia_chi }}" style="width: 40%;">
		</div>

		<div class="form-group">
			<label>Số Điện Thoại</label>
			<input class="form-control" id="sdt" type="text" name="so_dien_thoai" value="{{ $sinh_vien -> so_dien_thoai }}" style="width: 40%;">
		</div>

		<div class="form-group">
			<label>Email</label>
			<input class="form-control" type="email" id="email" name="email" value="{{ $sinh_vien -> email }}" style="width: 40%;">
		</div>
		<div class="form-group">
			<label>lớp</label>
			<select name = "ma_lop" class="form-control" id="lop" style="width: 40%; text-align: center;">
				@foreach ($lop as $array_lop)
					<option value="{{ $array_lop -> ma}}"
							@if ($sinh_vien -> ma_lop  == $array_lop -> ma )
							selected
							@endif>{{ $array_lop -> ten_lop }}</option>
				@endforeach
			</select>
		</div>
		<button class="btn btn-primary waves-effect waves-light mr-1">Sửa</button>
		<button type="reset" class="btn btn-secondary waves-effect">Khôi phục</button>
	</form>
</body>
</html>
@endsection